### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by uccmen** [karpathy/makemore#7]
<img width="472" alt="Screenshot 2022-12-20 at 10 01 43 AM" src="https://user-images.githubusercontent.com/1238697/208563701-f32b9c7e-dc5a-4f60-a31f-4836adf2efbc.png">

Tried running it the first time and seeing this.

**Comment by gakada** [comment]
Using Python 2? Need a recent enough version of Python 3.

**Comment by uccmen** [comment]
@gakada thank you this solves it. I'm new to python 😇
